************************************************************
ADULTS ADULTS ADULTS ADULTS ADULTS ADULTS ADULTS ADULTS ADULTS
**************************************************************;
LIBNAME INLIB "INSERT HS FILE";
DATA WORK.HS_COPY; SET INLIB.HS; RUN;

DATA HS_COPY; SET HS_COPY;
IF DHH_AGE =<18 THEN DELETE; RUN; 

*****************************************************************
01102018: BMI CORRECTION + DGAI CALCULATION ON CCHS 2015 - ADULTS
*****************************************************************;
*THERE ARE THREE SCENARIOS: 1) MEASURED BMI AVAILABLE, 2) MEASURED UNAVAIL BUT SELF-REPORT AVAIL, 3) NEITHER AVAIL*;
DATA FINAL_ADULTS; SET HS_COPY;
IF MHWGBMI < 999 THEN BMICORRECTION = 0; 				   *THESE PPL ARE FINE, NO CORRECTION NEEDED*;
IF MHWGWTK > 999 OR MHWGHTM > 9 THEN BMICORRECTION = 1; *THESE PPL NEED CORRECTION*;
IF MHWGBMI > 999 AND HWTGBMI > 999 THEN BMICORRECTION = 2; *THESE PPL MUST BE IMPUTED*;
RUN;

*CHECK*;
PROC FREQ DATA=FINAL_ADULTS; TABLE BMICORRECTION; RUN;

*NOW DO CORRECTION*;
***NOTE: THESE CUT-OFFS/CORRECTION FACTORS TO CORRECT SELF-REPORTED BMI ARE EXTERNAL, FROM A HEALTH REPORTS PAPER (SHIELDS ET AL. 2006. HEALTH REP)***;
DATA FINAL_ADULTS; SET FINAL_ADULTS;
IF BMICORRECTION = 1 AND DHH_SEX = 1 THEN NEWBMI = -1.08 + (1.08*HWTGBMI);
IF BMICORRECTION = 1 AND DHH_SEX = 2 THEN NEWBMI = -0.12 + (1.05*HWTGBMI);
IF BMICORRECTION = 0 THEN NEWBMI = MHWGBMI;
RUN;
*06/17/2020: LOOKS GOOD -- BMICORRECTION = 2 NEEDS TO BE IMPUTED*;

PROC FREQ DATA=FINAL_ADULTS; TABLE NEWBMI BMICORRECTION; RUN;

PROC FREQ DATA=FINAL_ADULTS; TABLE MHWGBMI; RUN;

*********************************************************
MAKE BMI CATEGORIES (DO NOT! REMOVE UNDERWEIGHT) - ADULTS
*********************************************************;
DATA FINAL_ADULTS; SET FINAL_ADULTS;
NEWBMI1 = ROUND(NEWBMI,0.01); RUN;

*3-CATEGORY OBESITY*;
DATA FINAL_ADULTS; SET FINAL_ADULTS;
IF NEWBMI1 < 18.5 THEN MBMI = 0; *UNDERWEIGHT*;
IF 18.5 =< NEWBMI1 =< 24.99 THEN MBMI = 1; *NORMAL WEIGHT*;
IF 25 =< NEWBMI1 =< 29.99 THEN MBMI = 2;  *OVERWEIGHT*;
IF 30 =< NEWBMI1 =< 34.99 THEN MBMI = 3; *OBESE CLASS I*;
IF 35 =< NEWBMI1 =< 39.99 THEN MBMI = 3; *OBESE CLASS II*;
IF NEWBMI1 >= 40 THEN MBMI = 3; *OBESE CLASS III*;
RUN;

PROC FREQ DATA=FINAL_ADULTS; TABLE MBMI; RUN;

********************************
PHYSICAL ACTIVITY - 18Y AND OVER
********************************;
PROC FREQ DATA=FINAL_ADULTS; TABLE PHSGAPA; RUN;

*FLAG MISSING FOR IMPUTATION*;
DATA PAL; SET FINAL_ADULTS;
IF PHSGAPA>99 THEN PHYSICAL_ACTIVITY=2;
ELSE PHYSICAL_ACTIVITY=1;
RUN;
*PHYSICAL_ACTIVITY = 2 NEEDS TO BE IMPUTED*;

PROC FREQ DATA=PAL; TABLE PHYSICAL_ACTIVITY; RUN;

*DIVIDE PHSGAPA BY 7 TO GET A ROUGH AVERAGE PER DAY, AND MULTIPLE BY 60 TO GET AVERAGE IN MINUTES*;
DATA PAL; SET PAL;
IF PHYSICAL_ACTIVITY=1 THEN PALDAYMIN = (PHSGAPA/7)*60; 
ELSE PALDAYMIN = "."; RUN;

PROC FREQ DATA=PAL; TABLE PALDAYMIN; RUN;
PROC FREQ DATA=PAL; TABLE PHYSICAL_ACTIVITY; RUN;

DATA PAL; SET PAL;
IF PHSFPPA = 2 OR PALDAYMIN <30 THEN PAL_1 = 1; *IF NO MODERATE/VIGOROUS EXERCISE OR < 30 MIN/DAY, THEN SEDENTARY*;
IF PHSFPPA = 1 AND 30 <= PALDAYMIN < 60 THEN PAL_1 = 2; *IF MODERATE/VIGOROUS EXERCISE BETWEEN 30-60 MIN/DAY, THEN LOW ACTIVE*;
IF PHSFPPA = 1 AND 60 <= PALDAYMIN < 180 THEN PAL_1 = 3; *IF MODERATE/VIGOROUS EXERCISE IS 60-180 MIN/DAY, THEN ACTIVE*;
IF PHSFPPA = 1 AND PALDAYMIN >=180 THEN PAL_1 = 4; *IF MODERATE/VIGOROUS EXERCISE IS > 180 MIN/DAY THEN VERY ACTIVE*;
IF PHYSICAL_ACTIVITY=2 THEN PAL_1 = "."; RUN;
RUN;

PROC FREQ DATA=PAL; TABLE PHSFPPA; RUN;
PROC FREQ DATA=PAL; TABLE PAL_1; RUN;

PROC FREQ DATA=PAL; TABLE PHSGAPA; RUN;

DATA PAL; SET PAL;
IF PHYSICAL_ACTIVITY=2 THEN PAL_1=1; RUN; 

*******************************
*****  NOW CALCULATE EER  *****
*******************************;
PROC FREQ DATA=PAL; TABLE MHWGWTK MHWGHTM; RUN;
*THERE ARE MISSING FOR MHWGWTK MHWGHTM -- MAKE A DATASET WITH NO MISSING, CALCULATE EER USING IOM FOR THOSE FIRST*;

DATA EER_IOM_ADULTS; SET PAL; 
IF BMICORRECTION=2 THEN DELETE; RUN;

PROC FREQ DATA=EER_IOM_ADULTS; TABLE BMICORRECTION; RUN;

*NOW CALCULATE EER FOR ADULTS (19 AND OVER);

***NOTE: THESE EQUATIONS ARE THE IOM EQUATIONS FOR CALCULATING EER, FOUND EXTERNALLY OR IN THE CCHS NUTRITION REF GUIDE, PG 67 (APPENDIX 2)***;
*BOYS NORMAL WEIGHT*;
*pal=1*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=1 AND PAL_1=1 AND DHH_AGE>=19
THEN EER= 661.8- (9.53 * DHH_AGE)+ ((15.91* MHWGWTK)+ (539.6* MHWGHTM));
RUN;

PROC FREQ DATA=EER_IOM_ADULTS; TABLE EER; RUN;

*EER=2*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=1 AND PAL_1=2 AND DHH_AGE>=19
THEN EER= 661.8- (9.53 * DHH_AGE)+ (1.11*(15.91* MHWGWTK)+ (539.6* MHWGHTM));
RUN;

*EER=3*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=1 AND PAL_1=3 AND DHH_AGE>=19
THEN EER= 661.8- (9.53 * DHH_AGE)+ (1.25*(15.91* MHWGWTK)+ (539.6* MHWGHTM));
RUN;

*EER=4*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=1 AND PAL_1>=4 AND DHH_AGE>=19
THEN EER= 661.8- (9.53 * DHH_AGE)+ (1.48*(15.91* MHWGWTK)+ (539.6* MHWGHTM));
RUN;

*NOW GIRLS OVER 19*;
*pal=1*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=2 AND PAL_1=1 AND DHH_AGE>=19
THEN EER= 354.1- (6.91 * DHH_AGE)+ (((9.36* MHWGWTK)+ (726* MHWGHTM)));
RUN;

*pal=2*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=2 AND PAL_1=2 AND DHH_AGE>=19
THEN EER= 354.1- (6.91 * DHH_AGE)+ (1.12*((9.36* MHWGWTK)+ (726* MHWGHTM)));
RUN;

*EER=3*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=2 AND PAL_1=3 AND DHH_AGE>=19
THEN EER= 354.1- (6.91 * DHH_AGE)+ (1.27*((9.36* MHWGWTK)+ (726* MHWGHTM)));
RUN;

*EER=4*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=2 AND PAL_1>=4 AND DHH_AGE>=19
THEN EER= 354.1- (6.91 * DHH_AGE)+ (1.45*((9.36* MHWGWTK)+ (726* MHWGHTM)));
RUN;

*******************************************************************************
*NOW OVERWEIGHT ADULTS;
*******************************************************************************;
*BOYS OVER WEIGHT*;
*pal=1*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=2 AND DHH_SEX=1 AND PAL_1=1 AND DHH_AGE>=19
THEN EER= 1085.6- (10.08 * DHH_AGE)+ (((13.7* MHWGWTK)+ (416* MHWGHTM)));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=3 AND DHH_SEX=1 AND PAL_1=1 AND DHH_AGE>=19
THEN EER= 1085.6- (10.08 * DHH_AGE)+ (((13.7* MHWGWTK)+ (416* MHWGHTM)));
RUN;

*pal=2*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=2 AND DHH_SEX=1 AND PAL_1=2 AND DHH_AGE>=19
THEN EER= 1085.6- (10.08 * DHH_AGE)+ (1.12*((13.7* MHWGWTK)+ (416* MHWGHTM)));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=3 AND DHH_SEX=1 AND PAL_1=2 AND DHH_AGE>=19
THEN EER= 1085.6- (10.08 * DHH_AGE)+ (1.12*((13.7* MHWGWTK)+ (416* MHWGHTM)));
RUN;

*pal=3*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=2 AND DHH_SEX=1 AND PAL_1=3 AND DHH_AGE>=19
THEN EER= 1085.6- (10.08 * DHH_AGE)+ (1.29*((13.7* MHWGWTK)+ (416* MHWGHTM)));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=3 AND DHH_SEX=1 AND PAL_1=3 AND DHH_AGE>=19
THEN EER= 1085.6- (10.08 * DHH_AGE)+ (1.29*((13.7* MHWGWTK)+ (416* MHWGHTM)));
RUN;

*pal=4*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=2 AND DHH_SEX=1 AND PAL_1>=4 AND DHH_AGE>=19
THEN EER= 1085.6- (10.08 * DHH_AGE)+ (1.59*((13.7* MHWGWTK)+ (416* MHWGHTM)));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=3 AND DHH_SEX=1 AND PAL_1>=4 AND DHH_AGE>=19
THEN EER= 1085.6- (10.08 * DHH_AGE)+ (1.59*((13.7* MHWGWTK)+ (416* MHWGHTM)));
RUN;

PROC FREQ DATA=EER_IOM_ADULTS; TABLE EER; RUN;

*NOW GIRLS OVER 19*;
*pal=1*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=2 AND DHH_SEX=2 AND PAL_1=1 AND DHH_AGE>=19 
THEN EER= 447.6- (7.95 * DHH_AGE)+ ((11.4* MHWGWTK)+ (619* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=3 AND DHH_SEX=2 AND PAL_1=1 AND DHH_AGE>=19 
THEN EER= 447.6- (7.95 * DHH_AGE)+ ((11.4* MHWGWTK)+ (619* MHWGHTM));
RUN;

*pal=2*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=2 AND DHH_SEX=2 AND PAL_1=2 AND DHH_AGE>=19 
THEN EER= 447.6- (7.95 * DHH_AGE)+ (1.16*(11.4* MHWGWTK)+ (619* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=3 AND DHH_SEX=2 AND PAL_1=2 AND DHH_AGE>=19 
THEN EER= 447.6- (7.95 * DHH_AGE)+ (1.16*(11.4* MHWGWTK)+ (619* MHWGHTM));
RUN;

*pal=3*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=2 AND DHH_SEX=2 AND PAL_1=3 AND DHH_AGE>=19 
THEN EER= 447.6- (7.95 * DHH_AGE)+ (1.27*(11.4* MHWGWTK)+ (619* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=3 AND DHH_SEX=2 AND PAL_1=3 AND DHH_AGE>=19 
THEN EER= 447.6- (7.95 * DHH_AGE)+ (1.27*(11.4* MHWGWTK)+ (619* MHWGHTM));
RUN;

*pal=4*;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=2 AND DHH_SEX=2 AND PAL_1>=4 AND DHH_AGE>=19 
THEN EER= 447.6- (7.95 * DHH_AGE)+ (1.44*(11.4* MHWGWTK)+ (619* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=3 AND DHH_SEX=2 AND PAL_1>=4 AND DHH_AGE>=19 
THEN EER= 447.6- (7.95 * DHH_AGE)+ (1.44*(11.4* MHWGWTK)+ (619* MHWGHTM));
RUN;

PROC FREQ DATA=EER_IOM_ADULTS; TABLE EER; RUN;
*705 MISSING MUST BE THE 18Y OLDS*;

*******************************************************************************
*NOW NORMAL WEIGHT 18Y OLDS;
*******************************************************************************;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=1 AND PAL_1=1 AND DHH_AGE=18  
THEN EER= 88.5- (61.9 * DHH_AGE)+ ((26.7* MHWGWTK)+(903* MHWGHTM))+25;
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=1 AND PAL_1=2 AND DHH_AGE=18  
THEN EER= 88.5- (61.9 * DHH_AGE)+ (1.13*(26.7* MHWGWTK)+(903* MHWGHTM))+25;
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=1 AND PAL_1=3 AND DHH_AGE=18  
THEN EER= 88.5- (61.9 * DHH_AGE)+ (1.26*(26.7* MHWGWTK)+(903* MHWGHTM))+25;
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=1 AND PAL_1=4 AND DHH_AGE=18  
THEN EER= 88.5- (61.9 * DHH_AGE)+ (1.42*(26.7* MHWGWTK)+(903* MHWGHTM))+25;
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=2 AND PAL_1=1 AND DHH_AGE=18  
THEN EER= 135.3- (30.8 * DHH_AGE)+ ((10.0* MHWGWTK)+(934* MHWGHTM))+25;
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=2 AND PAL_1=2 AND DHH_AGE=18  
THEN EER= 135.3- (30.8 * DHH_AGE)+ (1.16*(10.0* MHWGWTK)+(934* MHWGHTM))+25;
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=2 AND PAL_1=3 AND DHH_AGE=18  
THEN EER= 135.3- (30.8 * DHH_AGE)+ (1.31*(10.0* MHWGWTK)+(934* MHWGHTM))+25;
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=1 AND DHH_SEX=2 AND PAL_1=4 AND DHH_AGE=18  
THEN EER= 135.3- (30.8 * DHH_AGE)+ (1.56*(10.0* MHWGWTK)+(934* MHWGHTM))+25;
RUN;

PROC FREQ DATA=EER_IOM_ADULTS; TABLE EER; RUN;
*482 MISSING MUST BE OVERWEIGHT 18Y OLDS*;
DATA DATA.EER_IOM_ADULTS; SET EER_IOM_ADULTS; RUN;

*******************************************************************************
*NOW OVERWEIGHT 18Y OLDS;
*******************************************************************************;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=1 AND PAL_1=0 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ ((19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=1 AND PAL_1=0 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ ((19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=1 AND PAL_1=1 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ ((19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=1 AND PAL_1=1 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ ((19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=1 AND PAL_1=2 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ (1.12*(19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=1 AND PAL_1=2 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ (1.12*(19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=1 AND PAL_1=3 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ (1.24*(19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=1 AND PAL_1=3 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ (1.24*(19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=1 AND PAL_1=4 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ (1.45*(19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=1 AND PAL_1=4 AND DHH_AGE=18  
THEN EER= 114.1- (50.9 * DHH_AGE)+ (1.45*(19.5* MHWGWTK)+ (1161.4* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=2 AND PAL_1=0 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ ((15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=2 AND PAL_1=0 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ ((15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=2 AND PAL_1=1 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ ((15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=2 AND PAL_1=1 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ ((15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=2 AND PAL_1=2 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ (1.18*(15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=2 AND PAL_1=2 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ (1.18*(15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=2 AND PAL_1=3 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ (1.35*(15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=2 AND PAL_1=3 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ (1.35*(15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;

DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 2 AND DHH_SEX=2 AND PAL_1=4 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ (1.60*(15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI= 3 AND DHH_SEX=2 AND PAL_1=4 AND DHH_AGE=18  
THEN EER= 389.2- (41.2 * DHH_AGE)+ (1.60*(15* MHWGWTK)+ (701.6* MHWGHTM));
RUN;

PROC FREQ DATA=EER_IOM_ADULTS; TABLE EER; RUN;
DATA DATA.EER_IOM_ADULTS; SET EER_IOM_ADULTS; RUN;


PROC FREQ DATA=EER_IOM_ADULTS; TABLE MBMI; RUN;
DATA EER_IOM_ADULTS; SET EER_IOM_ADULTS;
IF MBMI=0 THEN DELETE; RUN;
*REMOVED UNDERWEIGHT*;

*******************************************************************************************
*NOW CALCULATE EER ON A DATASET OF MEASURED WEIGHT/HEIGHT MISSING, USING USDA SPECIFICATION
*******************************************************************************************;
DATA EER_USDA_ADULTS; SET PAL; 
IF BMICORRECTION < 2 THEN DELETE; RUN;

PROC FREQ DATA=EER_USDA_ADULTS; TABLE BMICORRECTION; RUN;

*MAKE A VARIABLE FOR USDA PHYSICAL ACTIVITY*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF PAL_1=1 THEN USDAPA = 1; *USDA SEDENTARY*;
IF PAL_1=2 THEN USDAPA = 2; *USDA MODERATELY ACTIVE*;
IF PAL_1 >=3 THEN USDAPA = 3; *USDA ACTIVE*;
RUN;

PROC FREQ DATA=EER_USDA_ADULTS; TABLE USDAPA PAL_1; RUN;
PROC FREQ DATA=EER_USDA_ADULTS; TABLE PHYSICAL_ACTIVITY; RUN;

***NOTE: THESE EER LEVELS (E.G. EER1 = 2400) ARE EXTERNAL LEVELS DEFINED IN THE USDA DIETARY GUIDELINES FOR AMERICANS 2015***;
*18Y OLD FIRST*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND DHH_AGE=18 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=2 AND DHH_AGE=18 THEN EER = 2800; 
IF DHH_SEX=1 AND USDAPA=3 AND DHH_AGE=18 THEN EER = 3200; 

IF DHH_SEX=2 AND USDAPA=1 AND DHH_AGE=18 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=2 AND DHH_AGE=18 THEN EER = 2000; 
IF DHH_SEX=2 AND USDAPA=3 AND DHH_AGE=18 THEN EER = 2400; RUN;

*19-20*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 19<=DHH_AGE<=20 THEN EER = 2600; 
IF DHH_SEX=1 AND USDAPA=2 AND 19<=DHH_AGE<=20 THEN EER = 2800; 
IF DHH_SEX=1 AND USDAPA=3 AND 19<=DHH_AGE<=20 THEN EER = 3000; 

IF DHH_SEX=2 AND USDAPA=1 AND 19<=DHH_AGE<=20 THEN EER = 2000; 
IF DHH_SEX=2 AND USDAPA=2 AND 19<=DHH_AGE<=20 THEN EER = 2200; 
IF DHH_SEX=2 AND USDAPA=3 AND 19<=DHH_AGE<=20 THEN EER = 2400; RUN;

*21-25*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 21<=DHH_AGE<=25 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=2 AND 21<=DHH_AGE<=25 THEN EER = 2800; 
IF DHH_SEX=1 AND USDAPA=3 AND 21<=DHH_AGE<=25 THEN EER = 3000; 

IF DHH_SEX=2 AND USDAPA=1 AND 21<=DHH_AGE<=25 THEN EER = 2000; 
IF DHH_SEX=2 AND USDAPA=2 AND 21<=DHH_AGE<=25 THEN EER = 2200; 
IF DHH_SEX=2 AND USDAPA=3 AND 21<=DHH_AGE<=25 THEN EER = 2400; RUN;

*26-30*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 26<=DHH_AGE<=30 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=2 AND 26<=DHH_AGE<=30 THEN EER = 2600; 
IF DHH_SEX=1 AND USDAPA=3 AND 26<=DHH_AGE<=30 THEN EER = 3000; 

IF DHH_SEX=2 AND USDAPA=1 AND 26<=DHH_AGE<=30 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=2 AND 26<=DHH_AGE<=30 THEN EER = 2000; 
IF DHH_SEX=2 AND USDAPA=3 AND 26<=DHH_AGE<=30 THEN EER = 2400; RUN;

*31-35*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 31<=DHH_AGE<=35 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=2 AND 31<=DHH_AGE<=35 THEN EER = 2600; 
IF DHH_SEX=1 AND USDAPA=3 AND 31<=DHH_AGE<=35 THEN EER = 3000; 

IF DHH_SEX=2 AND USDAPA=1 AND 31<=DHH_AGE<=35 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=2 AND 31<=DHH_AGE<=35 THEN EER = 2000; 
IF DHH_SEX=2 AND USDAPA=3 AND 31<=DHH_AGE<=35 THEN EER = 2200; RUN;

*36-40*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 36<=DHH_AGE<=40 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=2 AND 36<=DHH_AGE<=40 THEN EER = 2600; 
IF DHH_SEX=1 AND USDAPA=3 AND 36<=DHH_AGE<=40 THEN EER = 2800; 

IF DHH_SEX=2 AND USDAPA=1 AND 36<=DHH_AGE<=40 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=2 AND 36<=DHH_AGE<=40 THEN EER = 2000; 
IF DHH_SEX=2 AND USDAPA=3 AND 36<=DHH_AGE<=40 THEN EER = 2200; RUN;

*41-45*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 41<=DHH_AGE<=45 THEN EER = 2200; 
IF DHH_SEX=1 AND USDAPA=2 AND 41<=DHH_AGE<=45 THEN EER = 2600; 
IF DHH_SEX=1 AND USDAPA=3 AND 41<=DHH_AGE<=45 THEN EER = 2800; 

IF DHH_SEX=2 AND USDAPA=1 AND 41<=DHH_AGE<=45 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=2 AND 41<=DHH_AGE<=45 THEN EER = 2000; 
IF DHH_SEX=2 AND USDAPA=3 AND 41<=DHH_AGE<=45 THEN EER = 2200; RUN;

*46-50*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 46<=DHH_AGE<=50 THEN EER = 2200; 
IF DHH_SEX=1 AND USDAPA=2 AND 46<=DHH_AGE<=50 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=3 AND 46<=DHH_AGE<=50 THEN EER = 2800; 

IF DHH_SEX=2 AND USDAPA=1 AND 46<=DHH_AGE<=50 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=2 AND 46<=DHH_AGE<=50 THEN EER = 2000; 
IF DHH_SEX=2 AND USDAPA=3 AND 46<=DHH_AGE<=50 THEN EER = 2200; RUN;

*51-55*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 51<=DHH_AGE<=55 THEN EER = 2200; 
IF DHH_SEX=1 AND USDAPA=2 AND 51<=DHH_AGE<=55 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=3 AND 51<=DHH_AGE<=55 THEN EER = 2800; 

IF DHH_SEX=2 AND USDAPA=1 AND 51<=DHH_AGE<=55 THEN EER = 1600; 
IF DHH_SEX=2 AND USDAPA=2 AND 51<=DHH_AGE<=55 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=3 AND 51<=DHH_AGE<=55 THEN EER = 2200; RUN;

*56-60*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 56<=DHH_AGE<=60 THEN EER = 2200; 
IF DHH_SEX=1 AND USDAPA=2 AND 56<=DHH_AGE<=60 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=3 AND 56<=DHH_AGE<=60 THEN EER = 2600; 

IF DHH_SEX=2 AND USDAPA=1 AND 56<=DHH_AGE<=60 THEN EER = 1600; 
IF DHH_SEX=2 AND USDAPA=2 AND 56<=DHH_AGE<=60 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=3 AND 56<=DHH_AGE<=60 THEN EER = 2200; RUN;

*61-65*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 61<=DHH_AGE<=65 THEN EER = 2000; 
IF DHH_SEX=1 AND USDAPA=2 AND 61<=DHH_AGE<=65 THEN EER = 2400; 
IF DHH_SEX=1 AND USDAPA=3 AND 61<=DHH_AGE<=65 THEN EER = 2600; 

IF DHH_SEX=2 AND USDAPA=1 AND 61<=DHH_AGE<=65 THEN EER = 1600; 
IF DHH_SEX=2 AND USDAPA=2 AND 61<=DHH_AGE<=65 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=3 AND 61<=DHH_AGE<=65 THEN EER = 2000; RUN;

*66-70*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 66<=DHH_AGE<=70 THEN EER = 2000; 
IF DHH_SEX=1 AND USDAPA=2 AND 66<=DHH_AGE<=70 THEN EER = 2200; 
IF DHH_SEX=1 AND USDAPA=3 AND 66<=DHH_AGE<=70 THEN EER = 2600; 

IF DHH_SEX=2 AND USDAPA=1 AND 66<=DHH_AGE<=70 THEN EER = 1600; 
IF DHH_SEX=2 AND USDAPA=2 AND 66<=DHH_AGE<=70 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=3 AND 66<=DHH_AGE<=70 THEN EER = 2000; RUN;

*71-75*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND 71<=DHH_AGE<=75 THEN EER = 2000; 
IF DHH_SEX=1 AND USDAPA=2 AND 71<=DHH_AGE<=75 THEN EER = 2200; 
IF DHH_SEX=1 AND USDAPA=3 AND 71<=DHH_AGE<=75 THEN EER = 2600; 

IF DHH_SEX=2 AND USDAPA=1 AND 71<=DHH_AGE<=75 THEN EER = 1600; 
IF DHH_SEX=2 AND USDAPA=2 AND 71<=DHH_AGE<=75 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=3 AND 71<=DHH_AGE<=75 THEN EER = 2000; RUN;

*76+*;
DATA EER_USDA_ADULTS; SET EER_USDA_ADULTS;
IF DHH_SEX=1 AND USDAPA=1 AND DHH_AGE>75 THEN EER = 2000; 
IF DHH_SEX=1 AND USDAPA=2 AND DHH_AGE>75 THEN EER = 2200; 
IF DHH_SEX=1 AND USDAPA=3 AND DHH_AGE>75 THEN EER = 2400; 

IF DHH_SEX=2 AND USDAPA=1 AND DHH_AGE>75 THEN EER = 1600; 
IF DHH_SEX=2 AND USDAPA=2 AND DHH_AGE>75 THEN EER = 1800; 
IF DHH_SEX=2 AND USDAPA=3 AND DHH_AGE>75 THEN EER = 2000; RUN;

PROC FREQ DATA=EER_USDA_ADULTS; TABLE EER; RUN;



*COMBINE TWO DATASETS*;
PROC SORT DATA=EER_IOM_ADULTS; BY ADM_RNO; RUN;
PROC SORT DATA=EER_USDA_ADULTS; BY ADM_RNO; RUN;

DATA EERFINAL_ADULTS; MERGE EER_IOM_ADULTS EER_USDA_ADULTS; BY ADM_RNO; RUN;

PROC FREQ DATA=EERFINAL_ADULTS; TABLE MBMI; RUN;

***********************
NOW DEFINE MISREPORTERS
***********************;
DATA EERFINAL_ADULTS; SET EERFINAL_ADULTS;
ERATIO=FSDDEKC/EER;
RUN;

PROC FREQ DATA=EERFINAL_ADULTS; TABLE ERATIO; RUN;

***NOTE: THESE MISREPORTER CUT-OFFS ARE DEFINED EXTERNALLY IN GARRIGUET. 2018. HEALTH REP***;
DATA EERFINAL_ADULTS; SET EERFINAL_ADULTS;
IF ERATIO < 0.7 THEN MISREPORTER=1;
IF ERATIO > 1.42 THEN MISREPORTER=3;
IF 0.7=<ERATIO=<1.42 THEN MISREPORTER=2;
RUN;

PROC FREQ DATA=EERFINAL_ADULTS; TABLE MISREPORTER; RUN;


